package com.completems.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonBackReference;
import lombok.*;

import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Size;

@DynamoDBTable(tableName = "Post")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder(toBuilder = true)
public class DynamoComment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @Size(min=1)
    @DynamoDBAttribute
    private String comment;

    @JsonBackReference
    @ManyToOne(fetch = FetchType.LAZY)
    @DynamoDBAttribute
    DynamoPost post;
}
