package com.completems.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.completems.converter.LocalDateTimeConverter;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName = "Post")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder(toBuilder = true)
public class DynamoPost {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @Size(min=1)
    @DynamoDBAttribute
    private String name;

    @Size(min=1)
    @DynamoDBAttribute
    private String title;

    @Size(min=1)
    @Column(columnDefinition = "LONGTEXT")
    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt;

    @JsonManagedReference
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "post")
    @DynamoDBAttribute
    private List<DynamoComment> comments;

    public DynamoPost(String name, String title, String content, LocalDateTime now) {
        this.name = name;
        this.title = title;
        this.content = content;
        this.createdAt = now;
    }
}
